#spring.datasource.url: jdbc:mysql://localhost:3306/camundadb
spring.datasource.url: jdbc:mysql://camundadb.c6vqpjdjiikw.sa-east-1.rds.amazonaws.com:3306/camundadb
spring.datasource.username : root
spring.datasource.password : adminsgq
spring.datasource.driver-class-name : com.mysql.jdbc.Driver

#spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: adminsgq
  password: adminsgq